root_dir: ${oc.env:PWD}
server_compute_context:
  hardware:
    accelerator: auto
    devices: auto
  metrics_loggers:
    - name: wandb
      config:
        api_key_definition:
          env_var_name: WANDB_API_KEY
        params:
          project_name: "Pybiscus-FL"
          entity_name: "your-entity"
          run_name: "server-run"
          run_group: "fl-group"
          job_type: "server"
          is_client: false
server_run:
  num_rounds: '10'
  logger:
    name: rich
    config:
      empty_configuration: true
strategy:
  name: fedavg
  config:
    min_fit_clients: '2'
data:
  name: cifar
  config:
    dir_train: ${root_dir}/datasets/train/
    dir_val: ${root_dir}/datasets/val/
    dir_test: ${root_dir}/datasets/test/
    batch_size: '32'
    num_workers: '0'
model:
  name: cifar
  config:
    input_shape: '3'
    mid_shape: '6'
    n_classes: '10'
    lr: '0.001'
flower_server:
  listen_address: '[::]:3333'
