root_dir: ${oc.env:PWD}
num_clients: '3'
server_compute_context:
  hardware:
    accelerator: auto
    devices: auto
  metrics_logger:
    name: tensorboard
    config:
      subdir: /experiments/node
server_run:
  num_rounds: '10'
  epochs_per_round: '1'
  logger:
    name: rich
    config:
      empty_configuration: true
strategy:
  name: fedavg
  config:
    min_fit_clients: ${num_clients}
    min_evaluate_clients: ${num_clients}
    min_available_clients: ${num_clients}
data:
  name: pbr
  config:
    dir_train: None
    dir_val: None
    dir_test: ${root_dir}/datasets/test_INT_URITOX/
    augment: False
    cache_rate: '1.0'
    shape_img:
      - '96'
      - '96'
      - '96'
    batch_size: '1'
    num_workers: '4'
model:
  name: pbr
  config:
    spatial_dims: '3'
    in_channels: '1'
    out_channels: '4'
    channels:
      - '16'
      - '32'
      - '64'
      - '128'
      - '256'
    strides:
      - '2'
      - '2'
      - '2'
      - '2'
    num_res_units: '2'
    norm: "BATCH"
    lr: '0.001'
flower_server:
  listen_address: '[::]:3333'
